version: '2.0'
services:
  database:
    container_name: database
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/data
  agent:
    container_name: agent
    image: registry.gitlab.com/one37id/registry/solitaire/staging
    pull_policy: always
    restart: always
    depends_on:
      - database
      - redis
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MINIMUM_LOG_LEVEL=1
      - AGENT_SETUP_MODE=true
      - RECREATE_WORKFLOWS=false
      - DELETE_REDIS_CONFIG=false
      - KESTREL_PORT=80
      - AUTH_REQUEST_MAX_TTL_MINUTES=1
      - AUTH_BACKDOOR_SECRET_KEY=Hash
      - AUTH_SECRET_KEY=API_SECRET_KEY
      - AUTH_NONCE_TTL_MINUTES=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
